### ISSUE TITLE
Replace elm-analyse

### ISSUE THREAD

**Issue by sparksp** [sparksp/elm-review-config#3]
List of elm-analyse things to replace...

- elm compiler
    - [x] [FileLoadFailed](https://stil4m.github.io/elm-analyse/#/messages/FileLoadFailed)
    - [x] [UnnecessaryPortModule](https://stil4m.github.io/elm-analyse/#/messages/UnnecessaryPortModule)
- [elm-format]
    - [x] [DuplicateImport](https://stil4m.github.io/elm-analyse/#/messages/DuplicateImport)
    - [x] [DuplicateImportedVariable](https://stil4m.github.io/elm-analyse/#/messages/DuplicateImportedVariable)
    - [x] [UnnecessaryParens](https://stil4m.github.io/elm-analyse/#/messages/UnnecessaryParens)
- [NoBooleanCase] :package: (truqu/elm-review-nobooleancase)
    - [x] [BooleanCase](https://stil4m.github.io/elm-analyse/#/messages/BooleanCase)
- [NoDebug.Log] :package: (jfmengels/review-debug)
    - [x] [DebugLog](https://stil4m.github.io/elm-analyse/#/messages/DebugLog)
- [NoDebug.TodoOrToString] :package: (jfmengels/review-debug)
    - [x] [DebugTodo](https://stil4m.github.io/elm-analyse/#/messages/DebugTodo)
- [NoExposingEverything] :package: (jfmengels/review-common)
    - [x] [ExposeAll](https://stil4m.github.io/elm-analyse/#/messages/ExposeAll)
- [NoForbiddenWords] :package: (sparksp/elm-review-forbidden-words)
    - [x] [TriggerWords](https://stil4m.github.io/elm-analyse/#/messages/TriggerWords)
- [NoFullyAppliedPrefixOperator](https://github.com/jfmengels/review-simplification/blob/master/src/NoFullyAppliedPrefixOperator.elm)
    - [x] [NoUncurriedPrefix](https://stil4m.github.io/elm-analyse/#/messages/NoUncurriedPrefix)
- [NoImportingEverything] :package: (jfmengels/review-common)
    - [x] [ImportAll](https://stil4m.github.io/elm-analyse/#/messages/ImportAll)
- [NoMissingTypeAnnotation] :package: (jfmengels/review-common)
    - [x] [NoTopLevelSignature](https://stil4m.github.io/elm-analyse/#/messages/NoTopLevelSignature)
- [NoRedundantConcat] :package: (truqu/elm-review-noredundantconcat)
    - [x] [DropConcatOfLists](https://stil4m.github.io/elm-analyse/#/messages/DropConcatOfLists)
    - [x] [UnnecessaryListConcat](https://stil4m.github.io/elm-analyse/#/messages/UnnecessaryListConcat)
- [NoRedundantCons] :package: (truqu/elm-review-noredundantcons)
    - [x] [DropConsOfItemAndList](https://stil4m.github.io/elm-analyse/#/messages/DropConsOfItemAndList)
    - [x] [UseConsOverConcat](https://stil4m.github.io/elm-analyse/#/messages/UseConsOverConcat)
- [NoUnused.CustomTypeConstructors] :package: (jfmengels/review-unused)
    - [x] [UnusedValueConstructor](https://stil4m.github.io/elm-analyse/#/messages/UnusedValueConstructor)
- [NoUnused.Parameters] and [NoUnused.Patterns] :package: (jfmengels/review-unused)
    - [x] [UnusedPatternVariable](https://stil4m.github.io/elm-analyse/#/messages/UnusedPatternVariable)
- [NoUnused.Variables] :package: (jfmengels/review-unused)
    - [x] [UnusedImport](https://stil4m.github.io/elm-analyse/#/messages/UnusedImport)
    - [x] [UnusedImportAlias](https://stil4m.github.io/elm-analyse/#/messages/UnusedImportAlias)
    - [x] [UnusedImportedVariable](https://stil4m.github.io/elm-analyse/#/messages/UnusedImportedVariable)
    - [x] [UnusedTopLevel](https://stil4m.github.io/elm-analyse/#/messages/UnusedTopLevel)
    - [x] [UnusedTypeAlias](https://stil4m.github.io/elm-analyse/#/messages/UnusedTypeAlias)
    - [x] [UnusedVariable](https://stil4m.github.io/elm-analyse/#/messages/UnusedVariable)
- [elm-review-rules-to-avoid](https://github.com/sparksp/elm-review-rules-to-avoid) (unpublished)
    - [x] [FunctionInLet](https://stil4m.github.io/elm-analyse/#/messages/FunctionInLet)
    - [x] [MapNothingToNothing](https://stil4m.github.io/elm-analyse/#/messages/MapNothingToNothing)
    - [x] [MultiLineRecordFormatting](https://stil4m.github.io/elm-analyse/#/messages/MultiLineRecordFormatting)
    - [x] [SingleFieldRecord](https://stil4m.github.io/elm-analyse/#/messages/SingleFieldRecord)

[elm-format]: https://www.npmjs.com/package/elm-format
[NoBooleanCase]: https://package.elm-lang.org/packages/truqu/elm-review-nobooleancase/latest/NoBooleanCase
[NoDebug.Log]: https://package.elm-lang.org/packages/jfmengels/review-debug/latest/NoDebug-Log
[NoDebug.TodoOrToString]: https://package.elm-lang.org/packages/jfmengels/review-debug/latest/NoDebug-TodoOrToString
[NoExposingEverything]: https://package.elm-lang.org/packages/jfmengels/review-common/latest/NoExposingEverything
[NoForbiddenWords]: https://package.elm-lang.org/packages/sparksp/elm-review-forbidden-words/latest/NoForbiddenWords
[NoImportingEverything]: https://package.elm-lang.org/packages/jfmengels/review-common/latest/NoImportingEverything
[NoMissingTypeAnnotation]: https://package.elm-lang.org/packages/jfmengels/review-common/latest/NoMissingTypeAnnotation
[NoRedundantConcat]: https://package.elm-lang.org/packages/truqu/elm-review-noredundantconcat/latest/NoRedundantConcat
[NoRedundantCons]: https://package.elm-lang.org/packages/truqu/elm-review-noredundantcons/1.0.0/NoRedundantCons
[NoUnused.CustomTypeConstructors]: https://package.elm-lang.org/packages/jfmengels/review-unused/latest/NoUnused-CustomTypeConstructors
[NoUnused.Variables]: https://package.elm-lang.org/packages/jfmengels/review-unused/latest/NoUnused-Variables
[NoUnused.Parameters]: https://package.elm-lang.org/packages/jfmengels/review-unused/latest/NoUnused-Parameters
[NoUnused.Patterns]: https://package.elm-lang.org/packages/jfmengels/review-unused/latest/NoUnused-Patterns

**Comment by jfmengels** [comment]
Have been released: 
- https://package.elm-lang.org/packages/truqu/elm-review-noredundantcons/1.0.0/
- https://package.elm-lang.org/packages/truqu/elm-review-noleftpizza/1.0.0/
- https://package.elm-lang.org/packages/truqu/elm-review-nobooleancase/1.0.0/

**Comment by sparksp** [comment]
The remaining rules have been logged at https://github.com/sparksp/elm-review-rules-to-avoid/issues

**Comment by sparksp** [comment]
With [elm-review-rules-to-avoid](https://github.com/sparksp/elm-review-rules-to-avoid) now complete (albeit not published) all elm-analyse rules have been written!
